import { Nav } from '@/components/Nav'
import { ReactNode } from 'react'

export const metadata = {
  title: 'UrbanAvenue | Clothing',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <Nav id={''} quantity={0} />
      <div>{children}</div>
    </>
  )
}
