import { Nav } from "@/components/Nav";
import Head from "next/head";

export const metadata = {
  title: "UrbanAvenue | Clothing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
       
      </Head>
      <Nav />
      <div>{children}</div>
    </>
  );
}
