import { ReactNode } from 'react'

export const metadata = {
  title: 'UrbanAvenue | Panel Control',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return <div className="text-white">{children}</div>
}
