// These styles apply to every route in the application
import Head from "next/head";
import "./globals.css";
import { Vollkorn } from "@next/font/google";

const vollkorn = Vollkorn({
  subsets: ["latin"],
  display: 'swap',
  weight: "500",
});

export const metadata = {
  title: "UrbanAvenue | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className={`${vollkorn.className}`}>
      <Head>
       
      </Head>
      <body
        className={`scrollbar-thin scrollbar-track-white scrollbar-thumb-slate-300 bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
