import { ReactNode } from 'react'

export const metadata = {
  title: 'UrbanAvenue | Register',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return <>{children}</>
}
