"use client";

import PrivateRoute from "@/components/PrivateRoute";
import { checkIsPublicRoute } from "@/functions/check-is-public-route";
import { usePathname } from "next/navigation";

export const metadata = {
  title: "UrbanAvenue | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  const isPublicPage = checkIsPublicRoute(pathname);

  console.log(isPublicPage);

  return (
    <>
      {isPublicPage && null}
      {!isPublicPage && <PrivateRoute>children</PrivateRoute>}
    </>
  );
}
