import { Login } from '@/components/Login'

export const metadata = {
  title: 'UrbanAvenue | Sign in',
  description: 'Generated by create next app',
}

export default function Sign() {
  return (
    <div className="h-screen w-full bg-white text-black">
      <Login />
    </div>
  )
}
