const data = {

  product: [
    /* best-sellers */
    {
      title: "t-shirt-1",
      type: "best",
      id: "22",
      url: "/pageproduct/22",
      size: "G",
      image: "/t-shirt-1.jpg",
      price: 54.95,
      desc: "A best-selling t-shirt with a comfortable fit and stylish design.",
    },
    {
      title: "t-shirt-2",
      id: "23",
      type: "best",
      url: "/pageproduct/23",
      size: "G",
      image: "/t-shirt-2.jpg",
      price: 60.95,
      desc: "Another best-selling t-shirt with a comfortable fit and stylish design.",
    },
    {
      title: "t-shirt-3",
      type: "best",
      id: "24",
      url: "/pageproduct/24",
      size: "G",
      image: "/t-shirt-3.jpg",
      price: 54.95,
      desc: "A best-selling t-shirt with a comfortable fit and stylish design.",
    },
    {
      title: "t-shrit-4",
      id: "25",
      type: "best",
      url: "/pageproduct/25",
      size: "G",
      image: "/cap-1.jpg",
      price: 60.95,
      desc: "A best-selling t-shirt with a comfortable fit and stylish design.",
    },

    /* t-shirts 👕 */

    {
      title: "t-shirt-1",
      type: "tshirt",
      id: "1",
      url: "/pageproduct/1",
      size: "G",
      image: "/t-shirt-1.jpg",
      price: 54.95,
      desc: "A comfortable and stylish t-shirt.",
    },
    {
      title: "t-shrit-2",
      id: "2",
      type: "tshirt",
      url: "/pageproduct/2",
      size: "G",
      image: "/t-shirt-2.jpg",
      price: 60.95,
      desc: "A comfortable and stylish t-shirt.",
    },
    {
      title: "t-shirt-3",
      id: "3",
      type: "tshirt",
      url: "/pageproduct/3",
      size: "M",
      image: "/t-shirt-3.jpg",
      price: 67.8,
      desc: "A comfortable and stylish t-shirt.",
    },
    {
      title: "t-shirt-4",
      id: "4",
      type: "tshirt",
      url: "/pageproduct/4",
      size: "G",
      image: "/t-shirt-1.jpg",
      price: 150,
      desc: "A comfortable and stylish t-shirt.",
    },
    {
      title: "t-shirt-5",
      id: "5",
      type: "tshirt",
      url: "/pageproduct/5",
      size: "P",
      image: "/t-shirt-1.jpg",
      price: 130.99,
      desc: "A comfortable and stylish t-shirt.",
    },
    {
      title: "t-shirt-6",
      id: "6",
      type: "tshirt",
      url: "/pageproduct/6",
      size: "P",
      image: "/t-shirt-3.jpg",
      price: 130,
      desc: "A comfortable and stylish t-shirt.",
    },

    {
      title: "t-shirt-7",
      id: "7",
      type: "tshirt",
      url: "/pageproduct/7",
      size: "G",
      image: "/t-shirt-2.jpg",
      desc: "Stay cool and comfortable all day with this classic cotton t-shirt. Featuring a relaxed fit and a bold graphic print on the front, this t-shirt is perfect for casual wear or a night out with friends.",
      price: 155,
    },
    {
      title: "t-shirt-8",
      id: "8",
      type: "tshirt",
      url: "/pageproduct/8",
      size: "P",
      image: "/t-shirt-3.jpg",
      desc: "Add some edge to your wardrobe with this stylish t-shirt. Featuring a unique graphic print on the front and a comfortable fit, this t-shirt is perfect for those who want to stand out from the crowd.",
      price: 130,
    },
    {
      title: "t-shirt-9",
      id: "9",
      type: "tshirt",
      url: "/pageproduct/9",
      size: "G",
      image: "/t-shirt-2.jpg",
      desc: "Upgrade your wardrobe with this sleek and stylish t-shirt. Made from premium materials and featuring a bold graphic print on the front, this t-shirt is perfect for any fashion-forward individual.",
      price: 125,
    },
    {
      title: "t-shirt-10",
      id: "10",
      type: "tshirt",
      url: "/pageproduct/10",
      size: "P",
      image: "/t-shirt-2.jpg",
      desc: "Keep it casual and comfortable with this classic cotton t-shirt. Featuring a relaxed fit and a simple design, this t-shirt is perfect for everyday wear.",
      price: 125,
    },
    {
      title: "t-shirt-11",
      id: "11",
      type: "tshirt",
      url: "/pageproduct/11",
      size: "P",
      image: "/t-shirt-3.jpg",
      desc: "Make a statement with this bold graphic t-shirt. Featuring a unique design on the front and a comfortable fit, this t-shirt is perfect for those who want to express their individuality.",
      price: 130,
    },
    {
      title: "t-shirt-12",
      id: "12",
      type: "tshirt",
      url: "/pageproduct/12",
      size: "M",
      image: "/t-shirt-3.jpg",
      desc: "Elevate your style with this sophisticated t-shirt. Featuring a minimalistic design and a high-quality construction, this t-shirt is perfect for any occasion.",
      price: 129.9,
    },
    {
      title: "t-shirt-13",
      id: "13",
      type: "tshirt",
      url: "/pageproduct/13",
      size: "M",
      image: "/t-shirt-2.jpg",
      desc: "Step up your fashion game with this trendy t-shirt. Featuring a unique graphic print and a comfortable fit, this t-shirt is perfect for those who want to make a statement.",
      price: 137,
    },

    /* Cap 🧢 */
    {
      title: "cap-1",
      id: "14",
      type: "cap",
      url: "/pageproduct/14",
      image: "/cap-1.jpg",
      price: 59.9,
      desc: "Stay cool and stylish with our trendy cap-1. Made from high-quality materials, it's perfect for any casual occasion. Available in different colors.",
    },
    {
      title: "cap-2",
      id: "15",
      type: "cap",
      url: "/pageproduct/15",
      image: "/cap-2.jpg",
      price: 54.95,
      desc: "Make a statement with our cap-2. Featuring a unique design and comfortable fit, it's a must-have accessory for any fashion-forward individual.",
    },
    {
      title: "cap-3",
      id: "16",
      type: "cap",
      url: "/pageproduct/16",
      image: "/cap-3.jpg",
      price: 99.99,
      desc: "Upgrade your style game with our premium cap-3. Crafted from the finest materials and designed with attention to detail, it's the perfect accessory to complete your look.",
    },
    {
      title: "cap-4",
      id: "17",
      type: "cap",
      url: "/pageproduct/17",
      image: "/cap-5.jpg",
      price: 57.8,
      desc: "Add a touch of sophistication to your outfit with our classic cap-4. Made from durable materials, it's perfect for everyday wear and can be dressed up or down.",
    },
    {
      title: "cap-4",
      id: "27",
      type: "cap",
      url: "/pageproduct/27",
      image: "/cap-5.jpg",
      price: 57.8,
      desc: "Add a touch of sophistication to your outfit with our classic cap-4. Made from durable materials, it's perfect for everyday wear and can be dressed up or down.",
    },
    
    /* Shoe 👟 */
    {
      title: "shoe-1",
      id: "18",
      type: "shoe",
      url: "/pageproduct/18",
      image: "/jordan-3.jpg",
      price: 85.99,
      desc: "Step up your sneaker game with our shoe-1. Featuring a sleek design and comfortable fit, it's perfect for any casual occasion.",
    },
    
    {
      title: "shoe-2",
      id: "19",
      type: "shoe",
      url: "/pageproduct/19",
      image: "/shoe-1.jpg",
      price: 127.99,
      desc: "Stay on-trend with our shoe-2. Designed with both style and comfort in mind, it's the perfect addition to your footwear collection.",
    },
    
    {
      title: "shoe-3",
      id: "20",
      type: "shoe",
      url: "/pageproduct/20",
      image: "/jordan-3.jpg",
      price: 65.50,
      desc: "Get ready to turn heads with our shoe-3. Featuring a bold design and premium materials, it's a must-have for any sneaker enthusiast.",
    },
    
    {
      title: "shoe-4",
      id: "21",
      type: "shoe",
      url: "/pageproduct/21",
      image: "/court-1.jpg",
      desc: "Elevate your style with our shoe-4. Made from high-quality materials and designed with attention to detail, it's the perfect shoe for any occasion.",
      price: 104.99,
    },   
     
    {
      title: "shoe-5",
      id: "26",
      type: "shoe",
      url: "/pageproduct/26",
      image: "/allstart-1.jpg",
      desc: "Elevate your style with our shoe-4. Made from high-quality materials and designed with attention to detail, it's the perfect shoe for any occasion.",
      price: 104.99,
    },    
  ],
};

  user: [
    {
      id: 1,
      name:'Lucas',
      email:'amaralrdev@gmail.com',
    }
  ]

export default data;
