const data = {
    product: [
            /* best-sellers */
            {
              title: "t-shirt-1",
              type: "best",
              id: "22",
              url: "/pageproduct/22",
              size: "G",
              image: "/t-shirt-1.jpg",
              price: 54.95,
            },
            {
              title: "t-shirt-2",
              id: "23",
              type: "best",
              url: "/pageproduct/23",
              size: "G",
              image: "/t-shirt-2.jpg",
              price: 60.95,
            },
            {
              title: "t-shirt-3",
              type: "best",
              id: "24",
              url: "/pageproduct/24",
              size: "G",
              image: "/t-shirt-3.jpg",
              price: 54.95,
            },
            {
              title: "t-shrit-4",
              id: "25",
              type: "best",
              url: "/pageproduct/25",
              size: "G",
              image: "/cap-1.jpg",
              price: 60.95,
            },
        
            /* t-shirts 👕 */
        
            {
              title: "t-shirt-1",
              type: "tshirt",
              id: "1",
              url: "/pageproduct/1",
              size: "G",
              image: "/t-shirt-1.jpg",
              price: 54.95,
            },
            {
              title: "t-shrit-2",
              id: "2",
              type: "tshirt",
              url: "/pageproduct/2",
              size: "G",
              image: "/t-shirt-2.jpg",
              price: 60.95,
            },
            {
              title: "t-shirt-3",
              id: "3",
              type: "tshirt",
              url: "/pageproduct/3",
              size: "M",
              image: "/t-shirt-3.jpg",
              price: 67.8,
            },
            {
              title: "t-shirt-4",
              id: "4",
              type: "tshirt",
              url: "/pageproduct/4",
              size: "G",
              image: "/t-shirt-1.jpg",
              price: 150,
            },
            {
              title: "t-shirt-5",
              id: "5",
              type: "tshirt",
              url: "/pageproduct/5",
              size: "G",
              image: "/t-shirt-1.jpg",
              price: 130.99,
            },
            {
              title: "t-shirt-6",
              id: "6",
              type: "tshirt",
              url: "/pageproduct/6",
              size: "G",
              image: "/t-shirt-3.jpg",
              price: 130,
            },
            {
              title: "t-shirt-7",
              id: "7",
              type: "tshirt",
              url: "/pageproduct/7",
              size: "G",
              image: "/t-shirt-2.jpg",
              price: 155,
            },
            {
              title: "t-shirt-8",
              id: "8",
              type: "tshirt",
              url: "/pageproduct/8",
              size: "G",
              image: "/t-shirt-3.jpg",
              price: 130,
            },
            {
              title: "t-shirt-9",
              id: "9",
              type: "tshirt",
              url: "/pageproduct/9",
              size: "G",
              image: "/t-shirt-2.jpg",
              price: 125,
            },
            {
              title: "t-shirt-10",
              id: "10",
              type: "tshirt",
              url: "/pageproduct/10",
              size: "G",
              image: "/t-shirt-2.jpg",
              price: 125,
            },
            {
              title: "t-shirt-11",
              id: "11",
              type: "tshirt",
              url: "/pageproduct/11",
              size: "G",
              image: "/t-shirt-3.jpg",
              price: 130,
            },
            {
              title: "t-shirt-12",
              id: "12",
              type: "tshirt",
              url: "/pageproduct/12",
              size: "G",
              image: "/t-shirt-3.jpg",
              price: 129.9,
            },
            {
              title: "t-shirt-13",
              id: "13",
              type: "tshirt",
              url: "/pageproduct/13",
              size: "G",
              image: "/t-shirt-2.jpg",
              price: 137,
            },
        
            /* caps 🧢 */
        
            {
              title: "cap-1",
              id: "14",
              type: "cap",
              url: "/pageproduct/14",
              image: "/cap-1.jpg",
              price: 69.9,
            },
            {
              title: "cap-2",
              id: "15",
              type: "cap",
              url: "/pageproduct/15",
              image: "/cap-1.jpg",
              price: 74.95,
            },
            {
              title: "cap-3",
              id: "16",
              type: "cap",
              url: "/pageproduct/16",
              image: "/cap-1.jpg",
              price: 89.99,
            },
            {
              title: "cap-4",
              id: "17",
              type: "cap",
              url: "/pageproduct/17",
              image: "/cap-1.jpg",
              price: 67.8,
            },
        
            /* Shoe 👟 */
        
            {
              title: "shoe-1",
              id: "18",
              type: "shoe",
              url: "/pageproduct/18",
              image: "/jordan-3.jpg",
              price: 69.99,
            },
        
            {
              title: "shoe-2",
              id: "19",
              type: "shoe",
              url: "/pageproduct/19",
              image: "/shoe-1.jpg",
              price: 69.99,
            },
        
            {
              title: "shoe-3",
              id: "20",
              type: "shoe",
              url: "/pageproduct/20",
              image: "/jordan-3.jpg",
              price: 69.99,
            },
        
            {
              title: "shoe-4",
              id: "21",
              type: "shoe",
              url: "/pageproduct/21",
              image: "/court-1.jpg",
              price: 69.99,
            },
    ]
}

export default data;